def finish_programm(err):
    print(err)
    exit()